---
- name: Instalando no client
  hosts: localhost
  become: yes
  
  tasks:
  - name: Atualização de pacotes
    apt:
      upgrade: yes
      update_cache: yes
  - name: Instalando SDK
    apt: 
      name: openjdk-8-jdk
      update_cache: yes
  - name: Adicionando Repo
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
  - name: Adicionando no sources.list
    lineinfile:
      dest: /etc/apt/sources.list
      line: "deb https://pkg.jenkins.io/debian-stable binary/"
  - name: Instalando Jenkins
    apt: 
      name: jenkins
      update_cache: yes
  - name: Jenkins Service
    service:
      name: jenkins
      state: started
      enabled: yes
