---
- name: Instalando no client
  hosts: localhost
  become: yes
  
  tasks:
  - name: Atualização de pacotes
    yum: name=* state=latest

  - name: Fazendo download do repo
    get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/

  - name: Instalando o repo
    command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Instalando JDK
    yum: name=java state=latest update_cache=yes

  - name: Instalando Jenkins
    yum: name=jenkins state=latest update_cache=yes

  - name: Jenkins Service
    service:
      name: jenkins
      state: started
      enabled: yes
