---
- name: Instalando no client
  hosts: localhost
  become: yes
  
  tasks:
  - name: Atualização de pacotes
    yum: name=* state=latest

  - name: Fazendo download do rpm
    get_url: url=https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm dest=/root/
  
  - name: Instalando o repo
    command: rpm -ivh ~/mysql57-community-release-el7-9.noarch.rpm

  - name: Instalando MySQL
    yum: name=mysql-server state=latest update_cache=yes
 
  - name: MySQL Service
    service:
      name: mysqld
      state: started
      enabled: yes
