---
- name: Instalando no client
  hosts: localhost
  become: yes
  
  tasks:
  - name: Atualização de pacotes
    apt:
      upgrade: yes
      update_cache: yes
  - name: Instalando MySQL
    apt: pkg="{{ item }}"
    with_items:
      - mysql-server
      - mysql-client
  - name: MySQL Service
    service:
      name: mysql
      state: started
      enabled: yes
